repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: no-commit-to-branch
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint-docker
        args:
          - "-t"
          - "warning"

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        args:
          - "--external-sources"
          - "--source-path=SCRIPTDIR"

  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.40
    hooks:
      - id: pymarkdown
      - id: pymarkdown
        name: PyMarkdown Fix Lint findings
        args: [fix]
